"""
Task 12: answer writer and citation builder (design.md "Writing answers
and stories"; qna-mode requirements 3-7, 10).

The visitor's own model (not our server key) is given the retrieved
passages as numbered reference material (P1, P2, ...) and asked to
write from them, returning which numbers it actually used. Citations
are then built by OUR code from those numbers - never generated by the
model - so a citation can never name a passage that wasn't actually
retrieved, and its excerpt is always copied word for word from the
stored passage (design.md: "This means a citation cannot name a section
that does not exist, and an excerpt is always genuine").

Tone rules (no verdicts, plain English, no invented events - qna-mode
Requirement 10) are enforced at the PROMPT level only, not in code -
there's no reliable way to detect "did the model sneak in a verdict"
after the fact without another model call, and design.md doesn't ask
for one. This is a real limit worth knowing: a determined or careless
model could still violate the rule, and only eval-set spot-checking
(design.md's Testing Strategy, "spot-check 20 answers against their
cited sections") would catch it - this module can't guarantee it.
"""
import json

import llm_client

# Shared rules for every label - qna-mode Requirement 10 (tone) and
# design.md's "Writing answers and stories" rules.
_BASE_RULES = """Rules for your answer:
- Plain modern English, third person.
- Never state your own verdict on whether a person or action was right, wrong, a hero or a villain. If the text itself records a character or narrator giving a judgement, you may report that they said so, attributed and citable - but never state it as your own conclusion.
- Never tell the reader how they should act.
- Only use events, facts and reasoning that appear in the numbered passages below. Never add anything the passages don't support.
- Tell difficult or violent scenes plainly, at the level of the source material - don't soften or sensationalize.
- Base your answer only on the numbered passages given. If the passages don't actually support answering this question, say so honestly in your response rather than inventing content."""


def _build_context_block(passages: list[dict]) -> str:
    lines = []
    for i, p in enumerate(passages, start=1):
        meta = p["meta"]
        lines.append(f"[P{i}] ({meta['parva_name']}, Section {meta['section']}): {p.get('text', '')}")
    return "\n\n".join(lines)


def _factual_or_philosophical_prompt(label: str) -> str:
    return f"""You are answering a {label} question about the Mahabharata using only the numbered passages provided.

{_BASE_RULES}

Write a short answer of about 3 to 5 sentences.

Respond with ONLY a JSON object, no other text, no code fence:
{{"answer": "<your 3-5 sentence answer>", "used_ids": [<passage numbers you actually drew on, e.g. 1, 3>]}}"""


_AMBIGUOUS_PROMPT = f"""This question about the Mahabharata has both a factual side and a philosophical side. Using only the numbered passages provided, write ONE opening sentence for each side.

{_BASE_RULES}

Respond with ONLY a JSON object, no other text, no code fence:
{{"factual_sentence": "<one sentence, the factual reading>", "factual_ids": [<passage numbers used>], "philosophical_sentence": "<one sentence, the philosophical reading>", "philosophical_ids": [<passage numbers used>]}}"""


def _expand_prompt(label: str) -> str:
    kind = "ambiguous" if label == "ambiguous" else label
    return f"""You are expanding a short answer into fuller content for a {kind} question about the Mahabharata, using only the numbered passages provided. The reader already saw a short 3-5 sentence answer and asked to see more.

{_BASE_RULES}

Write about 150 to 250 words of fuller content: more of what the text actually says (more events, more of the reasoning, more of who said what), not just the short answer restated in different words.

Respond with ONLY a JSON object, no other text, no code fence:
{{"answer": "<150-250 word expanded answer>", "used_ids": [<passage numbers you actually drew on>]}}"""


def write_full_answer(
    provider: str,
    api_key: str,
    question: str,
    label: str,
    passages: list[dict],
    model: str | None = None,
) -> dict:
    """Task 13 / qna-mode Requirement 7 (Tell Me More): same contract as
    write_answer, but asks for fuller content on the same question rather
    than a short answer - always a single {"answer", "used_ids"} shape,
    even for a question originally classified ambiguous (Requirement
    7.2: "the full relevant content covering both readings" is one piece
    of expanded content, not two separate expansions)."""
    if label not in ("factual", "philosophical", "ambiguous"):
        raise ValueError(f"Unknown label: {label!r}")

    context = _build_context_block(passages)
    user_prompt = f"Question: {question}\n\nNumbered passages:\n{context}"

    response_text = llm_client.complete_safe(
        provider=provider,
        api_key=api_key,
        system=_expand_prompt(label),
        user=user_prompt,
        model=model,
        max_tokens=900,
    )

    try:
        return llm_client.extract_json(response_text)
    except (json.JSONDecodeError, ValueError):
        return {}


def write_answer(
    provider: str,
    api_key: str,
    question: str,
    label: str,
    passages: list[dict],
    model: str | None = None,
) -> dict:
    """passages: the merged hybrid-search results (search.hybrid_search's
    output), each with meta + text. Returns the model's raw structured
    response - use build_citations() next to turn used_ids into real
    Citations. Raises llm_client.LLMError on provider failure (auth,
    rate_limit, etc.) - callers should catch this per qna-mode
    Requirement 11."""
    if label not in ("factual", "philosophical", "ambiguous"):
        raise ValueError(f"Unknown label: {label!r}")

    context = _build_context_block(passages)
    system_prompt = (
        _AMBIGUOUS_PROMPT if label == "ambiguous"
        else _factual_or_philosophical_prompt(label)
    )
    user_prompt = f"Question: {question}\n\nNumbered passages:\n{context}"

    response_text = llm_client.complete_safe(
        provider=provider,
        api_key=api_key,
        system=system_prompt,
        user=user_prompt,
        model=model,
        max_tokens=500,
    )

    try:
        return llm_client.extract_json(response_text)
    except (json.JSONDecodeError, ValueError):
        # Model didn't follow the format - treat as "nothing usable" so
        # the caller falls through to the "text doesn't cover it" path
        # (qna-mode Requirement 9) rather than crashing or showing junk.
        return {}


def build_citations(used_ids: list, passages: list[dict]) -> list[dict]:
    """Turns model-reported passage numbers (1-indexed, matching
    _build_context_block's [P1], [P2], ...) into real citations, built
    entirely from our own retrieved passage data - never from anything
    the model wrote. Any id outside the valid range is silently dropped
    (design.md: "the citation is dropped and the answer is checked
    again" - the "checked again" part is the caller's job: an answer
    left with zero citations after dropping should not be shown as-is,
    see qna-mode Requirement 9.3)."""
    citations = []
    seen = set()
    for raw_id in used_ids or []:
        try:
            idx = int(raw_id)
        except (TypeError, ValueError):
            continue
        if idx < 1 or idx > len(passages) or idx in seen:
            continue
        seen.add(idx)
        meta = passages[idx - 1]["meta"]
        citations.append({
            "parva_name": meta["parva_name"],
            "section": meta["section"],
            "excerpt": passages[idx - 1].get("text", ""),
        })
    return citations


NO_ANSWER_MESSAGE = (
    "The text doesn't cover this directly. You might try asking about "
    "{suggestions} instead."
)


def suggest_related_topics(passages: list[dict], limit: int = 3) -> list[str]:
    """qna-mode Requirement 9.2: when declining for lack of an answer,
    suggest 2-3 related topics the text does cover. Uses whatever the
    search actually retrieved (even though it wasn't enough to answer
    the question) as the source of suggestions, rather than a separate
    static list - these are genuinely related to what was asked."""
    seen = set()
    suggestions = []
    for p in passages:
        parva = p["meta"]["parva_name"].title()
        if parva not in seen:
            seen.add(parva)
            suggestions.append(parva)
        if len(suggestions) >= limit:
            break
    return suggestions
